/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AcademicQuery {
  'id' : string,
  'status' : { 'resolved' : null } |
    { 'open' : null },
  'lastUpdateTimestamp' : bigint,
  'schoolId' : string,
  'queries' : string,
  'response' : [] | [string],
  'createdTimestamp' : bigint,
  'raisedBy' : Principal,
}
export interface AuditLog {
  'id' : string,
  'action' : string,
  'initiator' : Principal,
  'entityId' : string,
  'timestamp' : bigint,
  'details' : string,
  'entityType' : string,
}
export type ExternalBlob = Uint8Array;
export interface FilterCriteria {
  'filterEntityType' : [] | [string],
  'filterDateRange' : [] | [[bigint, bigint]],
  'filterEntityId' : [] | [string],
  'filterInitiator' : [] | [Principal],
}
export type PackingClass = { 'class1' : null } |
  { 'class2' : null } |
  { 'class3' : null } |
  { 'class4' : null } |
  { 'class5' : null } |
  { 'preSchool' : null };
export interface PackingCount {
  'theme' : PackingTheme,
  'addOnCount' : bigint,
  'totalCount' : bigint,
  'lastUpdateTimestamp' : bigint,
  'createdTimestamp' : bigint,
  'classType' : PackingClass,
  'packedCount' : bigint,
}
export interface PackingStatus {
  'kitCount' : bigint,
  'addOnCount' : bigint,
  'currentTheme' : string,
  'dispatched' : boolean,
  'dispatchDetails' : [] | [string],
  'lastUpdateTimestamp' : bigint,
  'schoolId' : string,
  'createdTimestamp' : bigint,
  'packed' : boolean,
}
export type PackingTheme = { 'themeA' : null } |
  { 'themeB' : null } |
  { 'themeC' : null } |
  { 'themeD' : null } |
  { 'themeE' : null };
export interface School {
  'id' : string,
  'city' : string,
  'name' : string,
  'contactPerson' : string,
  'email' : string,
  'website' : [] | [string],
  'state' : string,
  'lastUpdateTimestamp' : bigint,
  'address' : string,
  'createdTimestamp' : bigint,
  'contactNumber' : string,
  'studentCount' : bigint,
}
export interface StaffProfile {
  'principal' : Principal,
  'role' : StaffRole,
  'fullName' : string,
  'email' : string,
  'createdTimestamp' : bigint,
  'contactNumber' : string,
  'department' : string,
}
export type StaffRole = { 'admin' : null } |
  { 'marketing' : null } |
  { 'packing' : null } |
  { 'academic' : null } |
  { 'accounts' : null } |
  { 'training' : null };
export interface TrainingVisit {
  'id' : string,
  'visitingPerson' : string,
  'contactPersonMobile' : string,
  'visitDate' : bigint,
  'schoolId' : string,
  'createdTimestamp' : bigint,
  'classroomObservationProof' : [] | [ExternalBlob],
  'observations' : string,
  'reason' : string,
}
export interface UserProfile {
  'role' : StaffRole,
  'fullName' : string,
  'email' : string,
  'contactNumber' : string,
  'department' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createAcademicQuery' : ActorMethod<[string, string], string>,
  'createOrUpdatePackingCount' : ActorMethod<
    [string, PackingClass, PackingTheme, bigint, bigint, bigint],
    undefined
  >,
  'createOrUpdatePackingStatus' : ActorMethod<
    [string, bigint, bigint, boolean, boolean, [] | [string], string],
    undefined
  >,
  'createSchool' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      bigint,
    ],
    undefined
  >,
  'createStaffProfile' : ActorMethod<
    [Principal, string, StaffRole, string, string, string],
    undefined
  >,
  'createTrainingVisit' : ActorMethod<
    [string, bigint, string, string, string, string, [] | [ExternalBlob]],
    string
  >,
  'getAcademicQuery' : ActorMethod<[string], AcademicQuery>,
  'getAuditLog' : ActorMethod<[string], AuditLog>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFilteredAuditLogs' : ActorMethod<[FilterCriteria], Array<AuditLog>>,
  'getOutstandingAmount' : ActorMethod<[string], bigint>,
  'getOutstandingAmountsBySchoolIds' : ActorMethod<
    [Array<string>],
    Array<[string, bigint]>
  >,
  'getPackingCount' : ActorMethod<
    [string, PackingClass, PackingTheme],
    PackingCount
  >,
  'getPackingCountsBySchool' : ActorMethod<[string], Array<PackingCount>>,
  'getPackingStatus' : ActorMethod<[string], PackingStatus>,
  'getSchool' : ActorMethod<[string], School>,
  'getStaffProfile' : ActorMethod<[Principal], StaffProfile>,
  'getTrainingVisit' : ActorMethod<[string], TrainingVisit>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasOutstandingAmount' : ActorMethod<[string], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listAcademicQueriesBySchool' : ActorMethod<[string], Array<AcademicQuery>>,
  'listAllAcademicQueries' : ActorMethod<[], Array<AcademicQuery>>,
  'listAllAuditLogs' : ActorMethod<[], Array<AuditLog>>,
  'listAllPackingStatuses' : ActorMethod<[], Array<PackingStatus>>,
  'listAllSchools' : ActorMethod<[], Array<School>>,
  'listAllStaff' : ActorMethod<[], Array<StaffProfile>>,
  'listTrainingVisitsBySchool' : ActorMethod<[string], Array<TrainingVisit>>,
  'repairStaffProfilePermissions' : ActorMethod<[], bigint>,
  'respondToAcademicQuery' : ActorMethod<
    [string, string, { 'resolved' : null } | { 'open' : null }],
    undefined
  >,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setOutstandingAmount' : ActorMethod<[string, bigint], undefined>,
  'updateSchool' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      string,
      [] | [string],
      bigint,
    ],
    undefined
  >,
  'updateStaffProfile' : ActorMethod<
    [Principal, string, StaffRole, string, string, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];