/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const StaffRole = IDL.Variant({
  'admin' : IDL.Null,
  'marketing' : IDL.Null,
  'packing' : IDL.Null,
  'academic' : IDL.Null,
  'accounts' : IDL.Null,
  'training' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AcademicQuery = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Variant({ 'resolved' : IDL.Null, 'open' : IDL.Null }),
  'lastUpdateTimestamp' : IDL.Int,
  'schoolId' : IDL.Text,
  'queries' : IDL.Text,
  'response' : IDL.Opt(IDL.Text),
  'createdTimestamp' : IDL.Int,
  'raisedBy' : IDL.Principal,
});
export const AuditLog = IDL.Record({
  'id' : IDL.Text,
  'action' : IDL.Text,
  'initiator' : IDL.Principal,
  'entityId' : IDL.Text,
  'timestamp' : IDL.Int,
  'details' : IDL.Text,
  'entityType' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'role' : StaffRole,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'contactNumber' : IDL.Text,
  'department' : IDL.Text,
});
export const FilterCriteria = IDL.Record({
  'filterEntityType' : IDL.Opt(IDL.Text),
  'filterDateRange' : IDL.Opt(IDL.Tuple(IDL.Int, IDL.Int)),
  'filterEntityId' : IDL.Opt(IDL.Text),
  'filterInitiator' : IDL.Opt(IDL.Principal),
});
export const PackingStatus = IDL.Record({
  'kitCount' : IDL.Nat,
  'addOnCount' : IDL.Nat,
  'currentTheme' : IDL.Text,
  'dispatched' : IDL.Bool,
  'dispatchDetails' : IDL.Opt(IDL.Text),
  'lastUpdateTimestamp' : IDL.Int,
  'schoolId' : IDL.Text,
  'createdTimestamp' : IDL.Int,
  'packed' : IDL.Bool,
});
export const Payment = IDL.Record({
  'id' : IDL.Text,
  'paid' : IDL.Bool,
  'dueDate' : IDL.Int,
  'paymentProof' : IDL.Opt(ExternalBlob),
  'lastUpdateTimestamp' : IDL.Int,
  'schoolId' : IDL.Text,
  'createdTimestamp' : IDL.Int,
  'amount' : IDL.Nat,
});
export const School = IDL.Record({
  'id' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'contactPerson' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Opt(IDL.Text),
  'state' : IDL.Text,
  'lastUpdateTimestamp' : IDL.Int,
  'address' : IDL.Text,
  'createdTimestamp' : IDL.Int,
  'contactNumber' : IDL.Text,
  'studentCount' : IDL.Nat,
});
export const StaffProfile = IDL.Record({
  'principal' : IDL.Principal,
  'role' : StaffRole,
  'fullName' : IDL.Text,
  'email' : IDL.Text,
  'createdTimestamp' : IDL.Int,
  'contactNumber' : IDL.Text,
  'department' : IDL.Text,
});
export const TrainingVisit = IDL.Record({
  'id' : IDL.Text,
  'visitingPerson' : IDL.Text,
  'contactPersonMobile' : IDL.Text,
  'visitDate' : IDL.Int,
  'schoolId' : IDL.Text,
  'createdTimestamp' : IDL.Int,
  'classroomObservationProof' : IDL.Opt(ExternalBlob),
  'observations' : IDL.Text,
  'reason' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAcademicQuery' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'createOrUpdatePackingStatus' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Bool,
        IDL.Bool,
        IDL.Opt(IDL.Text),
        IDL.Text,
      ],
      [],
      [],
    ),
  'createPayment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Int], [IDL.Text], []),
  'createSchool' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Nat,
      ],
      [],
      [],
    ),
  'createStaffProfile' : IDL.Func(
      [IDL.Principal, IDL.Text, StaffRole, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'createTrainingVisit' : IDL.Func(
      [
        IDL.Text,
        IDL.Int,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(ExternalBlob),
      ],
      [IDL.Text],
      [],
    ),
  'getAcademicQuery' : IDL.Func([IDL.Text], [AcademicQuery], ['query']),
  'getAuditLog' : IDL.Func([IDL.Text], [AuditLog], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFilteredAuditLogs' : IDL.Func(
      [FilterCriteria],
      [IDL.Vec(AuditLog)],
      ['query'],
    ),
  'getPackingStatus' : IDL.Func([IDL.Text], [PackingStatus], ['query']),
  'getPayment' : IDL.Func([IDL.Text], [Payment], ['query']),
  'getSchool' : IDL.Func([IDL.Text], [School], ['query']),
  'getStaffProfile' : IDL.Func([IDL.Principal], [StaffProfile], ['query']),
  'getTrainingVisit' : IDL.Func([IDL.Text], [TrainingVisit], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAcademicQueriesBySchool' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AcademicQuery)],
      ['query'],
    ),
  'listAllAcademicQueries' : IDL.Func([], [IDL.Vec(AcademicQuery)], ['query']),
  'listAllAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
  'listAllPackingStatuses' : IDL.Func([], [IDL.Vec(PackingStatus)], ['query']),
  'listAllSchools' : IDL.Func([], [IDL.Vec(School)], ['query']),
  'listAllStaff' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
  'listPaymentsBySchool' : IDL.Func([IDL.Text], [IDL.Vec(Payment)], ['query']),
  'listTrainingVisitsBySchool' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(TrainingVisit)],
      ['query'],
    ),
  'respondToAcademicQuery' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Variant({ 'resolved' : IDL.Null, 'open' : IDL.Null }),
      ],
      [],
      [],
    ),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updatePayment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Int, IDL.Bool], [], []),
  'updateSchool' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Nat,
      ],
      [],
      [],
    ),
  'updateStaffProfile' : IDL.Func(
      [IDL.Principal, IDL.Text, StaffRole, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'uploadPaymentProof' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const StaffRole = IDL.Variant({
    'admin' : IDL.Null,
    'marketing' : IDL.Null,
    'packing' : IDL.Null,
    'academic' : IDL.Null,
    'accounts' : IDL.Null,
    'training' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AcademicQuery = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Variant({ 'resolved' : IDL.Null, 'open' : IDL.Null }),
    'lastUpdateTimestamp' : IDL.Int,
    'schoolId' : IDL.Text,
    'queries' : IDL.Text,
    'response' : IDL.Opt(IDL.Text),
    'createdTimestamp' : IDL.Int,
    'raisedBy' : IDL.Principal,
  });
  const AuditLog = IDL.Record({
    'id' : IDL.Text,
    'action' : IDL.Text,
    'initiator' : IDL.Principal,
    'entityId' : IDL.Text,
    'timestamp' : IDL.Int,
    'details' : IDL.Text,
    'entityType' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'role' : StaffRole,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'contactNumber' : IDL.Text,
    'department' : IDL.Text,
  });
  const FilterCriteria = IDL.Record({
    'filterEntityType' : IDL.Opt(IDL.Text),
    'filterDateRange' : IDL.Opt(IDL.Tuple(IDL.Int, IDL.Int)),
    'filterEntityId' : IDL.Opt(IDL.Text),
    'filterInitiator' : IDL.Opt(IDL.Principal),
  });
  const PackingStatus = IDL.Record({
    'kitCount' : IDL.Nat,
    'addOnCount' : IDL.Nat,
    'currentTheme' : IDL.Text,
    'dispatched' : IDL.Bool,
    'dispatchDetails' : IDL.Opt(IDL.Text),
    'lastUpdateTimestamp' : IDL.Int,
    'schoolId' : IDL.Text,
    'createdTimestamp' : IDL.Int,
    'packed' : IDL.Bool,
  });
  const Payment = IDL.Record({
    'id' : IDL.Text,
    'paid' : IDL.Bool,
    'dueDate' : IDL.Int,
    'paymentProof' : IDL.Opt(ExternalBlob),
    'lastUpdateTimestamp' : IDL.Int,
    'schoolId' : IDL.Text,
    'createdTimestamp' : IDL.Int,
    'amount' : IDL.Nat,
  });
  const School = IDL.Record({
    'id' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'contactPerson' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Opt(IDL.Text),
    'state' : IDL.Text,
    'lastUpdateTimestamp' : IDL.Int,
    'address' : IDL.Text,
    'createdTimestamp' : IDL.Int,
    'contactNumber' : IDL.Text,
    'studentCount' : IDL.Nat,
  });
  const StaffProfile = IDL.Record({
    'principal' : IDL.Principal,
    'role' : StaffRole,
    'fullName' : IDL.Text,
    'email' : IDL.Text,
    'createdTimestamp' : IDL.Int,
    'contactNumber' : IDL.Text,
    'department' : IDL.Text,
  });
  const TrainingVisit = IDL.Record({
    'id' : IDL.Text,
    'visitingPerson' : IDL.Text,
    'contactPersonMobile' : IDL.Text,
    'visitDate' : IDL.Int,
    'schoolId' : IDL.Text,
    'createdTimestamp' : IDL.Int,
    'classroomObservationProof' : IDL.Opt(ExternalBlob),
    'observations' : IDL.Text,
    'reason' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAcademicQuery' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'createOrUpdatePackingStatus' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Bool,
          IDL.Bool,
          IDL.Opt(IDL.Text),
          IDL.Text,
        ],
        [],
        [],
      ),
    'createPayment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Int], [IDL.Text], []),
    'createSchool' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'createStaffProfile' : IDL.Func(
        [IDL.Principal, IDL.Text, StaffRole, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'createTrainingVisit' : IDL.Func(
        [
          IDL.Text,
          IDL.Int,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
        ],
        [IDL.Text],
        [],
      ),
    'getAcademicQuery' : IDL.Func([IDL.Text], [AcademicQuery], ['query']),
    'getAuditLog' : IDL.Func([IDL.Text], [AuditLog], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFilteredAuditLogs' : IDL.Func(
        [FilterCriteria],
        [IDL.Vec(AuditLog)],
        ['query'],
      ),
    'getPackingStatus' : IDL.Func([IDL.Text], [PackingStatus], ['query']),
    'getPayment' : IDL.Func([IDL.Text], [Payment], ['query']),
    'getSchool' : IDL.Func([IDL.Text], [School], ['query']),
    'getStaffProfile' : IDL.Func([IDL.Principal], [StaffProfile], ['query']),
    'getTrainingVisit' : IDL.Func([IDL.Text], [TrainingVisit], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAcademicQueriesBySchool' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AcademicQuery)],
        ['query'],
      ),
    'listAllAcademicQueries' : IDL.Func(
        [],
        [IDL.Vec(AcademicQuery)],
        ['query'],
      ),
    'listAllAuditLogs' : IDL.Func([], [IDL.Vec(AuditLog)], ['query']),
    'listAllPackingStatuses' : IDL.Func(
        [],
        [IDL.Vec(PackingStatus)],
        ['query'],
      ),
    'listAllSchools' : IDL.Func([], [IDL.Vec(School)], ['query']),
    'listAllStaff' : IDL.Func([], [IDL.Vec(StaffProfile)], ['query']),
    'listPaymentsBySchool' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Payment)],
        ['query'],
      ),
    'listTrainingVisitsBySchool' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(TrainingVisit)],
        ['query'],
      ),
    'respondToAcademicQuery' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Variant({ 'resolved' : IDL.Null, 'open' : IDL.Null }),
        ],
        [],
        [],
      ),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updatePayment' : IDL.Func([IDL.Text, IDL.Nat, IDL.Int, IDL.Bool], [], []),
    'updateSchool' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Nat,
        ],
        [],
        [],
      ),
    'updateStaffProfile' : IDL.Func(
        [IDL.Principal, IDL.Text, StaffRole, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'uploadPaymentProof' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };